# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(432, 366)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.verticalTabWidget.setGeometry(QtCore.QRect(0, 0, 461, 341))
        self.verticalTabWidget.setObjectName("verticalTabWidget")
        self.szvmPage = QtWidgets.QWidget()
        self.szvmPage.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.szvmPage.setObjectName("szvmPage")
        self.szvmManButton = QtWidgets.QPushButton(self.szvmPage)
        self.szvmManButton.setGeometry(QtCore.QRect(30, 70, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.szvmManButton.setFont(font)
        self.szvmManButton.setObjectName("szvmManButton")
        self.szvmRaList = QtWidgets.QComboBox(self.szvmPage)
        self.szvmRaList.setGeometry(QtCore.QRect(30, 30, 171, 22))
        self.szvmRaList.setObjectName("szvmRaList")
        self.szvmServerLabel = QtWidgets.QLabel(self.szvmPage)
        self.szvmServerLabel.setGeometry(QtCore.QRect(280, 0, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.szvmServerLabel.setFont(font)
        self.szvmServerLabel.setObjectName("szvmServerLabel")
        self.szvmPopenButton = QtWidgets.QPushButton(self.szvmPage)
        self.szvmPopenButton.setGeometry(QtCore.QRect(220, 150, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.szvmPopenButton.setFont(font)
        self.szvmPopenButton.setObjectName("szvmPopenButton")
        self.szvmPopayButton = QtWidgets.QPushButton(self.szvmPage)
        self.szvmPopayButton.setGeometry(QtCore.QRect(30, 150, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.szvmPopayButton.setFont(font)
        self.szvmPopayButton.setObjectName("szvmPopayButton")
        self.szvmWprButton = QtWidgets.QPushButton(self.szvmPage)
        self.szvmWprButton.setGeometry(QtCore.QRect(220, 70, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.szvmWprButton.setFont(font)
        self.szvmWprButton.setObjectName("szvmWprButton")
        self.szvmServerList = QtWidgets.QComboBox(self.szvmPage)
        self.szvmServerList.setGeometry(QtCore.QRect(220, 30, 171, 22))
        self.szvmServerList.setObjectName("szvmServerList")
        self.szvmRaLabel = QtWidgets.QLabel(self.szvmPage)
        self.szvmRaLabel.setGeometry(QtCore.QRect(90, 0, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.szvmRaLabel.setFont(font)
        self.szvmRaLabel.setObjectName("szvmRaLabel")
        self.szvmPeButton = QtWidgets.QPushButton(self.szvmPage)
        self.szvmPeButton.setGeometry(QtCore.QRect(130, 230, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.szvmPeButton.setFont(font)
        self.szvmPeButton.setObjectName("szvmPeButton")
        self.verticalTabWidget.addTab(self.szvmPage, "")
        self.prbzPage = QtWidgets.QWidget()
        self.prbzPage.setObjectName("prbzPage")
        self.prbzManButton = QtWidgets.QPushButton(self.prbzPage)
        self.prbzManButton.setGeometry(QtCore.QRect(30, 70, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.prbzManButton.setFont(font)
        self.prbzManButton.setObjectName("prbzManButton")
        self.prbzServerLabel = QtWidgets.QLabel(self.prbzPage)
        self.prbzServerLabel.setGeometry(QtCore.QRect(280, 0, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.prbzServerLabel.setFont(font)
        self.prbzServerLabel.setObjectName("prbzServerLabel")
        self.prbzRaList = QtWidgets.QComboBox(self.prbzPage)
        self.prbzRaList.setGeometry(QtCore.QRect(30, 30, 171, 22))
        self.prbzRaList.setObjectName("prbzRaList")
        self.prbzPopayButton = QtWidgets.QPushButton(self.prbzPage)
        self.prbzPopayButton.setGeometry(QtCore.QRect(30, 150, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.prbzPopayButton.setFont(font)
        self.prbzPopayButton.setObjectName("prbzPopayButton")
        self.prbzWprButton = QtWidgets.QPushButton(self.prbzPage)
        self.prbzWprButton.setGeometry(QtCore.QRect(220, 70, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.prbzWprButton.setFont(font)
        self.prbzWprButton.setObjectName("prbzWprButton")
        self.prbzPeButton = QtWidgets.QPushButton(self.prbzPage)
        self.prbzPeButton.setGeometry(QtCore.QRect(130, 230, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.prbzPeButton.setFont(font)
        self.prbzPeButton.setObjectName("prbzPeButton")
        self.prbzServerList = QtWidgets.QComboBox(self.prbzPage)
        self.prbzServerList.setGeometry(QtCore.QRect(220, 30, 171, 22))
        self.prbzServerList.setObjectName("prbzServerList")
        self.prbzPopenButton = QtWidgets.QPushButton(self.prbzPage)
        self.prbzPopenButton.setGeometry(QtCore.QRect(220, 150, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.prbzPopenButton.setFont(font)
        self.prbzPopenButton.setObjectName("prbzPopenButton")
        self.prbzRaLabel = QtWidgets.QLabel(self.prbzPage)
        self.prbzRaLabel.setGeometry(QtCore.QRect(90, 0, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.prbzRaLabel.setFont(font)
        self.prbzRaLabel.setObjectName("prbzRaLabel")
        self.verticalTabWidget.addTab(self.prbzPage, "")
        self.edvPage = QtWidgets.QWidget()
        self.edvPage.setObjectName("edvPage")
        self.edvRaList = QtWidgets.QComboBox(self.edvPage)
        self.edvRaList.setGeometry(QtCore.QRect(30, 30, 171, 22))
        self.edvRaList.setObjectName("edvRaList")
        self.edvManButton = QtWidgets.QPushButton(self.edvPage)
        self.edvManButton.setGeometry(QtCore.QRect(30, 90, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.edvManButton.setFont(font)
        self.edvManButton.setObjectName("edvManButton")
        self.edvServerLabel = QtWidgets.QLabel(self.edvPage)
        self.edvServerLabel.setGeometry(QtCore.QRect(280, 0, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.edvServerLabel.setFont(font)
        self.edvServerLabel.setObjectName("edvServerLabel")
        self.edvWprButton = QtWidgets.QPushButton(self.edvPage)
        self.edvWprButton.setGeometry(QtCore.QRect(220, 90, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.edvWprButton.setFont(font)
        self.edvWprButton.setObjectName("edvWprButton")
        self.edvPopenButton = QtWidgets.QPushButton(self.edvPage)
        self.edvPopenButton.setGeometry(QtCore.QRect(220, 210, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.edvPopenButton.setFont(font)
        self.edvPopenButton.setObjectName("edvPopenButton")
        self.edvServerList = QtWidgets.QComboBox(self.edvPage)
        self.edvServerList.setGeometry(QtCore.QRect(220, 30, 171, 22))
        self.edvServerList.setObjectName("edvServerList")
        self.edvPodmoButton = QtWidgets.QPushButton(self.edvPage)
        self.edvPodmoButton.setGeometry(QtCore.QRect(30, 210, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.edvPodmoButton.setFont(font)
        self.edvPodmoButton.setObjectName("edvPodmoButton")
        self.edvRaLabel = QtWidgets.QLabel(self.edvPage)
        self.edvRaLabel.setGeometry(QtCore.QRect(90, 0, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.edvRaLabel.setFont(font)
        self.edvRaLabel.setObjectName("edvRaLabel")
        self.verticalTabWidget.addTab(self.edvPage, "")
        self.deductionPage = QtWidgets.QWidget()
        self.deductionPage.setObjectName("deductionPage")
        self.deductionMoButton = QtWidgets.QPushButton(self.deductionPage)
        self.deductionMoButton.setGeometry(QtCore.QRect(220, 90, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.deductionMoButton.setFont(font)
        self.deductionMoButton.setObjectName("deductionMoButton")
        self.deductionMoscowButton = QtWidgets.QPushButton(self.deductionPage)
        self.deductionMoscowButton.setGeometry(QtCore.QRect(30, 90, 171, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.deductionMoscowButton.setFont(font)
        self.deductionMoscowButton.setObjectName("deductionMoscowButton")
        self.deductionServerLabel = QtWidgets.QLabel(self.deductionPage)
        self.deductionServerLabel.setGeometry(QtCore.QRect(280, 0, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.deductionServerLabel.setFont(font)
        self.deductionServerLabel.setObjectName("deductionServerLabel")
        self.deductionServerList = QtWidgets.QComboBox(self.deductionPage)
        self.deductionServerList.setGeometry(QtCore.QRect(220, 30, 171, 22))
        self.deductionServerList.setObjectName("deductionServerList")
        self.deductionGuList = QtWidgets.QComboBox(self.deductionPage)
        self.deductionGuList.setGeometry(QtCore.QRect(30, 30, 171, 22))
        self.deductionGuList.setObjectName("deductionGuList")
        self.deductionGuLabel = QtWidgets.QLabel(self.deductionPage)
        self.deductionGuLabel.setGeometry(QtCore.QRect(100, 0, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.deductionGuLabel.setFont(font)
        self.deductionGuLabel.setObjectName("deductionGuLabel")
        self.verticalTabWidget.addTab(self.deductionPage, "")
        self.twinsPage = QtWidgets.QWidget()
        self.twinsPage.setObjectName("twinsPage")
        self.verticalTabWidget.addTab(self.twinsPage, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.verticalTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BDUtil"))
        self.szvmManButton.setText(_translate("MainWindow", "MAN"))
        self.szvmServerLabel.setText(_translate("MainWindow", "Сервер"))
        self.szvmPopenButton.setText(_translate("MainWindow", "POPEN"))
        self.szvmPopayButton.setText(_translate("MainWindow", "POPAY"))
        self.szvmWprButton.setText(_translate("MainWindow", "WPR"))
        self.szvmRaLabel.setText(_translate("MainWindow", "Район"))
        self.szvmPeButton.setText(_translate("MainWindow", "PE"))
        self.verticalTabWidget.setTabText(self.verticalTabWidget.indexOf(self.szvmPage), _translate("MainWindow", "Анализ работодателей"))
        self.prbzManButton.setText(_translate("MainWindow", "MAN"))
        self.prbzServerLabel.setText(_translate("MainWindow", "Сервер"))
        self.prbzPopayButton.setText(_translate("MainWindow", "POPAY"))
        self.prbzWprButton.setText(_translate("MainWindow", "WPR"))
        self.prbzPeButton.setText(_translate("MainWindow", "PE"))
        self.prbzPopenButton.setText(_translate("MainWindow", "POPEN"))
        self.prbzRaLabel.setText(_translate("MainWindow", "Район"))
        self.verticalTabWidget.setTabText(self.verticalTabWidget.indexOf(self.prbzPage), _translate("MainWindow", "ПРБЗ"))
        self.edvManButton.setText(_translate("MainWindow", "MAN"))
        self.edvServerLabel.setText(_translate("MainWindow", "Сервер"))
        self.edvWprButton.setText(_translate("MainWindow", "WPR"))
        self.edvPopenButton.setText(_translate("MainWindow", "POPEN"))
        self.edvPodmoButton.setText(_translate("MainWindow", "PODMO"))
        self.edvRaLabel.setText(_translate("MainWindow", "Район"))
        self.verticalTabWidget.setTabText(self.verticalTabWidget.indexOf(self.edvPage), _translate("MainWindow", "Индексация"))
        self.deductionMoButton.setText(_translate("MainWindow", "МО"))
        self.deductionMoscowButton.setText(_translate("MainWindow", "Москва"))
        self.deductionServerLabel.setText(_translate("MainWindow", "Сервер"))
        self.deductionGuLabel.setText(_translate("MainWindow", "ГУ"))
        self.verticalTabWidget.setTabText(self.verticalTabWidget.indexOf(self.deductionPage), _translate("MainWindow", "Удержания"))
        self.verticalTabWidget.setTabText(self.verticalTabWidget.indexOf(self.twinsPage), _translate("MainWindow", "Двойники"))

